#!/bin/bash

# first argument is the index of the first file. 
# Second argument is the number of threats per core.
# each machine will process 8 files at the same time.

sudo nice -n -19 taskset 1 python3 single_core_parser $(($1)) $2 &

sudo nice -n -19 taskset 2 python3 single_core_parser $(($1 + $2)) $2 &

sudo nice -n -19 taskset 4 python3 single_core_parser $(($1 + $2*2)) $2 &

sudo nice -n -19 taskset 8 python3 single_core_parser $(($1 + $2*3)) $2