#!/bin/bash

# the only argumen is the number of the node

sudo python3 single_core_coinbase_fix $1 1 &

sudo python3 single_core_coinbase_fix $1 2 &

sudo python3 single_core_coinbase_fix $1 3 &

sudo python3 single_core_coinbase_fix $1 4 