#!/bin/bash

# first argument is the index of the first file. 
# Second argument is the number of threats per core.
# each machine will process 8 files at the same time.

python3 single_core_parser $(($1)) $2 &

python3 single_core_parser $(($1 + $2)) $2 &

python3 single_core_parser $(($1 + $2*2)) $2 &

python3 single_core_parser $(($1 + $2*3)) $2