#!/usr/bin/python3

import argparse
import add_addresses

arg_parser = argparse.ArgumentParser(description='Multi-process blockchain address encoder from TXOs.')

arg_parser.add_argument('node_number', metavar='N', type=int, nargs=1,
                   help='Node number e.i. 1, 2, 3, 4 ... n')
arg_parser.add_argument('core_number', metavar='N', type=int, nargs=1,
                   help='core of the the computer to use. If it is a quadcore then it must be between 1 and 4.')


args = arg_parser.parse_args()
print(args.node_number, args.core_number)

add_addresses.main((args.node_number[0],args.core_number[0]))